// @ts-expect-error: generated by opennextjs-cloudflare build, not present until after build
import nextWorker from "../.open-next/worker.js";

export default {
  fetch: nextWorker.fetch,

  async scheduled(
    event: ScheduledEvent,
    env: CloudflareEnv & { WORKERS_URL: string; CRON_SECRET: string },
    ctx: ExecutionContext
  ) {
    const base = `https://${env.WORKERS_URL}`;
    if (event.cron === "*/5 * * * *") {
      ctx.waitUntil(
        fetch(`${base}/api/cron/parse-sweep`, {
          method: "POST",
          headers: { "x-cron-secret": env.CRON_SECRET },
        })
      );
    }
    if (event.cron === "0 9 * * *") {
      ctx.waitUntil(
        fetch(`${base}/api/cron/renewal-reminders`, {
          method: "POST",
          headers: { "x-cron-secret": env.CRON_SECRET },
        })
      );
    }
  },
};
