// @ts-expect-error: generated by opennextjs-cloudflare build, not present until after build
import nextWorker from "../.open-next/worker.js";
import { runParseSweep } from "../lib/cron/parse-sweep";
import { runProductEnrichment } from "../lib/cron/product-enrichment";
import { runAdminDigest } from "../lib/cron/admin-digest";
import { runRenewalReminders } from "../lib/cron/renewal-reminders";

export default {
  fetch: nextWorker.fetch,

  async scheduled(event: ScheduledEvent, env: CloudflareEnv, ctx: ExecutionContext) {
    // OpenNext populates process.env on the fetch path; scheduled() runs outside that
    // wrapper, so the cron functions (which use process.env.* via createServiceClient
    // and the email lib) need it set up manually here.
    for (const [key, value] of Object.entries(env as Record<string, unknown>)) {
      if (typeof value === "string") {
        (process.env as Record<string, string>)[key] = value;
      }
    }

    if (event.cron === "*/5 * * * *") {
      ctx.waitUntil(runParseSweep().catch((err) => console.error("[cron] parse-sweep failed:", err)));
    }
    if (event.cron === "*/15 * * * *") {
      ctx.waitUntil(runProductEnrichment().catch((err) => console.error("[cron] product-enrichment failed:", err)));
    }
    if (event.cron === "0 8 * * *") {
      ctx.waitUntil(runAdminDigest().catch((err) => console.error("[cron] admin-digest failed:", err)));
    }
    if (event.cron === "0 9 * * *") {
      ctx.waitUntil(runRenewalReminders().catch((err) => console.error("[cron] renewal-reminders failed:", err)));
    }
  },
};
