// @ts-expect-error: generated by opennextjs-cloudflare build, not present until after build
import nextWorker from "../.open-next/worker.js";
import { runParseSweep } from "../lib/cron/parse-sweep";
import { runProductEnrichment } from "../lib/cron/product-enrichment";
import { runAdminDigest } from "../lib/cron/admin-digest";
import { runRenewalReminders } from "../lib/cron/renewal-reminders";

export default {
  fetch: nextWorker.fetch,

  async scheduled(event: ScheduledEvent, _env: CloudflareEnv, ctx: ExecutionContext) {
    if (event.cron === "*/5 * * * *") {
      ctx.waitUntil(runParseSweep().catch((err) => console.error("[cron] parse-sweep failed:", err)));
    }
    if (event.cron === "*/15 * * * *") {
      ctx.waitUntil(runProductEnrichment().catch((err) => console.error("[cron] product-enrichment failed:", err)));
    }
    if (event.cron === "0 8 * * *") {
      ctx.waitUntil(runAdminDigest().catch((err) => console.error("[cron] admin-digest failed:", err)));
    }
    if (event.cron === "0 9 * * *") {
      ctx.waitUntil(runRenewalReminders().catch((err) => console.error("[cron] renewal-reminders failed:", err)));
    }
  },
};
